// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCs4j2u8GqxwZLER-_MEDCsEJjAc_-qZ0',
    appId: '1:271839725852:web:532525542b1b10d9b892d9',
    messagingSenderId: '271839725852',
    projectId: 'aplicativo-receitas-60dbc',
    authDomain: 'aplicativo-receitas-60dbc.firebaseapp.com',
    storageBucket: 'aplicativo-receitas-60dbc.firebasestorage.app',
    measurementId: 'G-BH0YLDBMZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPMkVg6qbaXKhm5HOHUq7ooLTQOKhRXVE',
    appId: '1:271839725852:android:e6b2919daa967acbb892d9',
    messagingSenderId: '271839725852',
    projectId: 'aplicativo-receitas-60dbc',
    storageBucket: 'aplicativo-receitas-60dbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACbGI4EQWLkiqK0iVC5iGn_HOfE6JEetw',
    appId: '1:271839725852:ios:8bee52bd3943a449b892d9',
    messagingSenderId: '271839725852',
    projectId: 'aplicativo-receitas-60dbc',
    storageBucket: 'aplicativo-receitas-60dbc.firebasestorage.app',
    iosBundleId: 'com.example.aplicativoReceitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACbGI4EQWLkiqK0iVC5iGn_HOfE6JEetw',
    appId: '1:271839725852:ios:8bee52bd3943a449b892d9',
    messagingSenderId: '271839725852',
    projectId: 'aplicativo-receitas-60dbc',
    storageBucket: 'aplicativo-receitas-60dbc.firebasestorage.app',
    iosBundleId: 'com.example.aplicativoReceitas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCs4j2u8GqxwZLER-_MEDCsEJjAc_-qZ0',
    appId: '1:271839725852:web:e0652987be9392d0b892d9',
    messagingSenderId: '271839725852',
    projectId: 'aplicativo-receitas-60dbc',
    authDomain: 'aplicativo-receitas-60dbc.firebaseapp.com',
    storageBucket: 'aplicativo-receitas-60dbc.firebasestorage.app',
    measurementId: 'G-BZC6N37NN6',
  );
}
